-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 13:47:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema appDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appDB` DEFAULT CHARACTER SET utf8 ;
USE `appDB` ;

-- -----------------------------------------------------
-- Table `appDB`.`trainers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appDB`.`trainers` (
  `tId` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `displayName` VARCHAR(20) NOT NULL,
  `DoB` DATETIME NOT NULL,
  `phoneNumber` INT NOT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `webpage` VARCHAR(45) NULL DEFAULT NULL,
  `pictureId` INT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `certifications` VARCHAR(100) NULL DEFAULT NULL,
  `specialities` VARCHAR(100) NULL DEFAULT NULL,
  `availability` DATETIME NULL DEFAULT NULL,
  `messageInbox` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`tId`),
  UNIQUE INDEX `id_UNIQUE` (`tId` ASC) VISIBLE,
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC) VISIBLE,
  UNIQUE INDEX `pictureId_UNIQUE` (`pictureId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appDB`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appDB`.`clients` (
  `cId` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `displayName` VARCHAR(20) NULL DEFAULT NULL,
  `DoB` DATETIME NOT NULL,
  `phoneNumber` INT NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `pictureId` INT NULL DEFAULT NULL,
  `paymentDetails` VARCHAR(45) NULL DEFAULT NULL,
  `messageInbox` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`cId`),
  UNIQUE INDEX `id_UNIQUE` (`cId` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC) VISIBLE,
  UNIQUE INDEX `pictureId_UNIQUE` (`pictureId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appDB`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appDB`.`schedules` (
  `sId` INT NOT NULL,
  `trainerId` INT NOT NULL,
  `clientId` INT NULL DEFAULT NULL,
  `eventDate` DATETIME NOT NULL,
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `details` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`sId`),
  UNIQUE INDEX `id_UNIQUE` (`sId` ASC) INVISIBLE,
  INDEX `tId_idx` (`trainerId` ASC) VISIBLE,
  INDEX `cId_idx` (`clientId` ASC) VISIBLE,
  CONSTRAINT `tId`
    FOREIGN KEY (`trainerId`)
    REFERENCES `appDB`.`trainers` (`tId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cId`
    FOREIGN KEY (`clientId`)
    REFERENCES `appDB`.`clients` (`cId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appDB`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appDB`.`message` (
  `mId` VARCHAR(45) NOT NULL,
  `senderId` INT NOT NULL,
  `receiverId` INT NOT NULL,
  `message` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`mId`),
  INDEX `id_idx1` (`senderId` ASC, `receiverId` ASC) VISIBLE,
  CONSTRAINT `tId`
    FOREIGN KEY (`senderId` , `receiverId`)
    REFERENCES `appDB`.`trainers` (`tId` , `tId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cId`
    FOREIGN KEY (`senderId` , `receiverId`)
    REFERENCES `appDB`.`clients` (`cId` , `cId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
